<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Version>1.0.1</Version>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<EnableHarmony>true</EnableHarmony>
		<EnableModZip>true</EnableModZip>
		<ModZipPath>$(ProjectDir)releases</ModZipPath>
		<EnableModDeploy>true</EnableModDeploy>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="releases\**" />
	  <EmbeddedResource Remove="releases\**" />
	  <None Remove="releases\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Content Packs\[CP] Campgrounds\manifest.json">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\defaultCampgroundPreview.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<ContentPacks Include="Content Packs\[CP] Campgrounds" Version="$(Version)" IgnoreModFilePaths="assets\maps\island_tilesheet_1.png, assets\maps\paths.png, assets\maps\spring_outdoorsTileSheet.png, assets\maps\spring_town.png, assets\maps\townInterior.png, assets\maps\townInterior_2.png, assets\maps\spring_outdoorsTileSheet2.png, assets\maps\walls_and_floors.png, assets\maps\spring_Waterfalls.png, assets\maps\spring_Shadows.png, assets\maps\spring_beach.png, assets\maps\Mines\mine.png" IgnoreModFilePatterns="\.aseprite$" />
		<ContentPacks Include="Content Packs\[CP] Cindersap Forest Campground" IgnoreModFilePaths="assets\maps\paths.png, assets\maps\spring_outdoorsTileSheet.png, assets\maps\spring_outdoorsTileSheet2.png, assets\maps\desert_festival_tilesheet.png" Version="$(Version)" IgnoreModFilePatterns="\.aseprite$" />
	</ItemGroup>
</Project>
